### Get tasks
GET http://localhost:3001

### Add new task
POST http://localhost:3001/new
Content-Type: application/json

{
    "description": "Test from REST Client 3"
}

### Delete task
DELETE http://localhost:3001/delete/1 HTTP/1.1


# Remote DB

### TestDB
GET https://todo-back-end-pwlr.onrender.com/test-db

### 
GET https://todo-back-end-pwlr.onrender.com/


### Add new task remote
POST https://todo-back-end-pwlr.onrender.com/new
Content-Type: application/json

{
    "description": "Test from REST Client"
}

### Delete task remote
DELETE https://todo-back-end-pwlr.onrender.com/delete/5 HTTP/1.1
